package com.keymane.domain.accounts;

import com.keymane.domain.BaseDomainObject;
import java.util.Date;

public class User extends BaseDomainObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.users.id
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.users.national_id
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    private Integer nationalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.users.email
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.users.first_name
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.users.last_name
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.users.phone_number
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.users.encrypted_password
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    private String encryptedPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.users.salt
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.users.last_login
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    private Date lastLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.users.created_at
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.users.updated_at
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table accounts.users
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.users.id
     *
     * @return the value of accounts.users.id
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.users.id
     *
     * @param id the value for accounts.users.id
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.users.national_id
     *
     * @return the value of accounts.users.national_id
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    public Integer getNationalId() {
        return nationalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.users.national_id
     *
     * @param nationalId the value for accounts.users.national_id
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    public void setNationalId(Integer nationalId) {
        this.nationalId = nationalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.users.email
     *
     * @return the value of accounts.users.email
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.users.email
     *
     * @param email the value for accounts.users.email
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.users.first_name
     *
     * @return the value of accounts.users.first_name
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.users.first_name
     *
     * @param firstName the value for accounts.users.first_name
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.users.last_name
     *
     * @return the value of accounts.users.last_name
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.users.last_name
     *
     * @param lastName the value for accounts.users.last_name
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.users.phone_number
     *
     * @return the value of accounts.users.phone_number
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.users.phone_number
     *
     * @param phoneNumber the value for accounts.users.phone_number
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.users.encrypted_password
     *
     * @return the value of accounts.users.encrypted_password
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    public String getEncryptedPassword() {
        return encryptedPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.users.encrypted_password
     *
     * @param encryptedPassword the value for accounts.users.encrypted_password
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    public void setEncryptedPassword(String encryptedPassword) {
        this.encryptedPassword = encryptedPassword == null ? null : encryptedPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.users.salt
     *
     * @return the value of accounts.users.salt
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.users.salt
     *
     * @param salt the value for accounts.users.salt
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.users.last_login
     *
     * @return the value of accounts.users.last_login
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    public Date getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.users.last_login
     *
     * @param lastLogin the value for accounts.users.last_login
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.users.created_at
     *
     * @return the value of accounts.users.created_at
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.users.created_at
     *
     * @param createdAt the value for accounts.users.created_at
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.users.updated_at
     *
     * @return the value of accounts.users.updated_at
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.users.updated_at
     *
     * @param updatedAt the value for accounts.users.updated_at
     *
     * @mbggenerated Wed Jun 29 14:01:54 EAT 2016
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}